task:
  name: SRLBot
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    envSpacing: 5
    episodeLength: 1200
    enableDebugVis: false
    cameraFollow: true
    controlFrequencyInv: 2
    clipActions: 1.0
    frame_stack: 5
    pdControl: true
    forceControl: true
    powerScale: 1.0
    headingWeight: 0.5
    upWeight: 0.1
    actionsCost: 0.01
    energyCost: 0.05
    dofVelocityScale: 0.1
    angularVelocityScale: 0.25
    contactForceScale: 0.01
    jointsAtLimitCost: 0.25
    deathCost: -1.0
    terminationHeight: 0.75
    gait_period: 18.0
    foot_clearance: 0.2
    alive_reward_scale: 0.0
    torques_cost_scale: 5.0e-06
    progress_reward_scale: 0.0
    dof_acc_cost_scale: 0.5
    dof_vel_cost_scale: 1
    dof_pos_cost_sacle: 0.05
    no_fly_penalty_scale: 10.0
    gait_similarity_penalty_scale: 10
    pelvis_height_reward_scale: 5.0
    orientation_reward_scale: 7
    tracking_ang_vel_reward_scale: 2.0
    vel_tracking_reward_scale: 6.0
    clearance_penalty_scale: 50
    lateral_distance_penalty_scale: 30
    actions_rate_scale: 0.1
    actions_smoothness_scale: 0.1
    asset:
      assetFileName: mjcf/srl_bot/srl_bot_inversed_v6.xml
    plane:
      staticFriction: 1.0
      dynamicFriction: 1.0
      restitution: 0.0
    enableCameraSensors: false
  sim:
    dt: 0.0166
    substeps: 2
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 4
      num_velocity_iterations: 0
      contact_offset: 0.02
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 10.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 8388608
      num_subscenes: ${....num_subscenes}
      contact_collection: 0
  task:
    randomize: false
    randomization_params:
      frequency: 600
      observations:
        range:
        - 0
        - 0.002
        operation: additive
        distribution: gaussian
      actions:
        range:
        - 0.0
        - 0.02
        operation: additive
        distribution: gaussian
      sim_params:
        gravity:
          range:
          - 0
          - 0.4
          operation: additive
          distribution: gaussian
          schedule: linear
          schedule_steps: 3000
      actor_params:
        humanoid:
          color: true
          rigid_body_properties:
            mass:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              setup_only: true
              schedule: linear
              schedule_steps: 3000
          rigid_shape_properties:
            friction:
              num_buckets: 500
              range:
              - 0.7
              - 1.3
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            restitution:
              range:
              - 0.0
              - 0.7
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
          dof_properties:
            damping:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            stiffness:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            lower:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
              schedule: linear
              schedule_steps: 3000
            upper:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
              schedule: linear
              schedule_steps: 3000
train:
  params:
    seed: ${...seed}
    algo:
      name: srl_bot_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 512
        - 256
        - 128
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:Humanoid,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      multi_gpu: ${....multi_gpu}
      mixed_precision: true
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 0.01
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0005
      lr_schedule: adaptive
      kl_threshold: 0.008
      score_to_win: 999999
      max_epochs: ${resolve_default:1000,${....max_iterations}}
      save_best_after: 200
      save_frequency: 1000
      print_stats: true
      grad_norm: 1.0
      entropy_coef: 0.005
      truncate_grads: true
      ppo: true
      e_clip: 0.2
      horizon_length: 32
      minibatch_size: 32768
      mini_epochs: 5
      critic_coef: 4
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.0001
      a_sym_loss_coef: 1.0
      c_sym_loss_coef: 0.0
pbt:
  enabled: false
task_name: ${task.name}
experiment: SRL_bot_v6_s2
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: 3000
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: /home/zdh232/mly/IGEvolution/isaacgymenvs/runs/SRL_bot_v6_s1_18-17-07-52/nn/SRL_bot_v6_s1.pth
sigma: ''
multi_gpu: false
wandb_activate: true
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: TRO_SRL_Evo
wandb_tags: []
wandb_logcode_dir: ''
capture_video: false
capture_video_freq: 1464
capture_video_len: 100
force_render: true
headless: true
experiment_dir: false
