task:
  name: HumanoidAMPSRLGym_s1_Smpl
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    envSpacing: 5
    episodeLength: 600
    cameraFollow: true
    enableDebugVis: true
    pdControl: true
    powerScale: 1.0
    controlFrequencyInv: 2
    stateInit: Random
    hybridInitProb: 0.5
    numAMPObsSteps: 2
    localRootObs: false
    contactBodies:
    - right_foot
    - left_foot
    - right_shin
    - left_shin
    terminationHeight: 0.5
    enableEarlyTermination: true
    motion_file: 56_01_cmu_amp.npy
    srl_endpos_obs: false
    asset:
      assetFileName: mjcf/amp_humanoid_180.xml
    plane:
      staticFriction: 1.0
      dynamicFriction: 1.0
      restitution: 0.0
    torque_threshold: 50
    upper_reward_w: 1
    srl_torque_reward_w: 0.001
    srl_load_cell_w: 0.0
    srl_root_force_reward_w: 0
    target_v_task: false
    autogen_model: true
    load_cell: true
    humanoid_load_cell_obs: false
    design_param_obs: false
    design_params:
      mode: mode1
      first_leg_lenth: 0.4
      first_leg_size: 0.03
      second_leg_lenth: 0.8
      second_leg_size: 0.03
      third_leg_size: 0.03
    freejoint_y: false
  sim:
    dt: 0.0166
    substeps: 2
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 4
      num_velocity_iterations: 0
      contact_offset: 0.02
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 10.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 8388608
      num_subscenes: ${....num_subscenes}
      contact_collection: 2
  task:
    randomize: false
    randomization_params:
      frequency: 600
      observations:
        range:
        - 0
        - 0.002
        operation: additive
        distribution: gaussian
      actions:
        range:
        - 0.0
        - 0.02
        operation: additive
        distribution: gaussian
      sim_params:
        gravity:
          range:
          - 0
          - 0.4
          operation: additive
          distribution: gaussian
          schedule: linear
          schedule_steps: 3000
      actor_params:
        humanoid:
          color: true
          rigid_body_properties:
            mass:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              setup_only: true
              schedule: linear
              schedule_steps: 3000
          rigid_shape_properties:
            friction:
              num_buckets: 500
              range:
              - 0.7
              - 1.3
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            restitution:
              range:
              - 0.0
              - 0.7
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
          dof_properties:
            damping:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            stiffness:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            lower:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
              schedule: linear
              schedule_steps: 3000
            upper:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
              schedule: linear
              schedule_steps: 3000
train:
  params:
    seed: ${...seed}
    algo:
      name: amp_continuous
    model:
      name: continuous_amp
    network:
      name: amp
      separate: true
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: -2.9
          fixed_sigma: true
          learn_sigma: false
      mlp:
        units:
        - 512
        - 256
        activation: relu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
      disc:
        units:
        - 1024
        - 512
        activation: relu
        initializer:
          name: default
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:HumanoidAMP_SMPL,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      ppo: true
      multi_gpu: ${....multi_gpu}
      mixed_precision: false
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 1
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 3.0e-05
      lr_schedule: constant
      kl_threshold: 0.008
      score_to_win: 20000
      max_epochs: ${resolve_default:5000,${....max_iterations}}
      save_best_after: 100
      save_frequency: 1000
      print_stats: true
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: false
      e_clip: 0.2
      horizon_length: 16
      minibatch_size: 32768
      mini_epochs: 6
      critic_coef: 5
      clip_value: false
      seq_len: 4
      bounds_loss_coef: 10
      amp_obs_demo_buffer_size: 200000
      amp_replay_buffer_size: 1000000
      amp_replay_keep_prob: 0.01
      amp_batch_size: 512
      amp_minibatch_size: 4096
      disc_coef: 5
      disc_logit_reg: 0.05
      disc_grad_penalty: 5
      disc_reward_scale: 2
      disc_weight_decay: 0.0001
      normalize_amp_input: true
      task_reward_w: 0.5
      disc_reward_w: 10
      actions_num_humanoid: 57
      actions_num_srl: 6
      train_srl_only: false
      humanoid_checkpoint: false
      hsrl_checkpoint: false
      mirror_loss: true
      sym_loss_coef: 1
      humanoid_obs_masked: false
      start_frame: 0
      model_output_file: false
      train_dir: runs
      save_data: false
      save_load_cell_data: false
  gym:
    design_opt: random
    GA_population_size: 20
    GA_num_iterations: 10
    GA_mutation_rate: 0.1
    GA_crossover_rate: 0.7
    GA_bounds_scale: 0.3
    BO_n_initial_points: 10
    BO_num_iterations: 100
    BO_initial_eval_epoch: 700
    RA_num_iterations: 100
pbt:
  enabled: false
task_name: ${task.name}
experiment: ''
num_envs: 4096
seed: 9890
torch_deterministic: false
max_iterations: 6000
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: /home/ps/pan1/files/zjh/zdh/IGEvolution-main/isaacgymenvs/runs/HumanoidAMP_SMPL_18-19-17-40/nn/HumanoidAMP_SMPL_18-19-17-45_2000.pth
sigma: ''
multi_gpu: false
wandb_activate: true
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: SRL
wandb_tags: []
wandb_logcode_dir: ''
capture_video: false
capture_video_freq: 1464
capture_video_len: 100
force_render: true
headless: true
experiment_dir: false
